import { Applewatch } from "./applewatch";

export const APPLEWATCH: Applewatch[] = [
  {
    id: 1,
    picture1:
      "https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP746/alu-spacegray-sp.jpg",
    picture2:
      "https://i5.walmartimages.com/asr/b91845e3-7cd1-4fdf-a1ca-c5553965a60a_1.c57721e160249974b34903261beb0260.jpeg",
    picture3:
      "https://static.fnac-static.com/multimedia/Images/FR/NR/b5/b9/74/7649717/1505-1/tsp20160927100415/Apple-Watch-Series-1-38-mm-Boitier-en-Aluminium-Or-avec-Bracelet-Sport-Gris-Ciment.jpg",
    name: "Apple Watch série 1",
    systeme: "WatchOS 3",
    systeme_compatible: "iOS 8 et plus",
    nombre_de_coeur: 2,
    processeur: "Apple S1p",
    capacite_de_stockage_disponible: "0 Mo",
    clavier: "Non",
    couleur: "Noire, Blanche, Blue, Rouge, Vert, Violet",
    tactile: "Oui",
    definition_de_l_écran: "272*340",
    reseau_wifi_supporte: "WI-Fi 802.11n",
    support_GPS: "Oui",
    fonction_appareil_photo: "Non",
    poids: "30 grammes",
    prix: "",
  },

  {
    id: 2,
    picture1:
      "https://static.fnac-static.com/multimedia/Images/FR/NR/64/76/7f/8353380/1540-1/tsp20160908202044/Apple-Watch-Series-2-38-mm-Boitier-en-Acier-inoxydable-avec-Bracelet-Sport-Blanc.jpg",
    picture2:
      "https://support.apple.com/library/APPLE/APPLECARE_ALLGEOS/SP746/alu-spacegray-nike.jpg",
    picture3:
      "https://static.fnac-static.com/multimedia/Images/FR/NR/57/76/7f/8353367/1505-1/tsp20160908202044/Apple-Watch-Series-2-38-mm-Boitier-en-Acier-inoxydable-avec-Bracelet-Boucle-moderne-Bleu-Nuit-Taille-L.jpg",
    name: "Apple Watch série 2",
    systeme: "WatchOS 3",
    systeme_compatible: "iOS 10",
    nombre_de_coeur: 2,
    processeur: "Apple S2",
    capacite_de_stockage_disponible: "0 Mo",
    clavier: "Non",
    couleur: "Noire, Blanche, Blue, Rouge, Vert, Violet",
    tactile: "Oui",
    definition_de_l_écran: "272*340",
    reseau_wifi_supporte: "WI-Fi 802.11n",
    support_GPS: "Oui",
    fonction_appareil_photo: "Non",
    poids: "28,2 grammes",
    prix: "",
  },
  {
    id: 3,
    picture1:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/FQL42?wid=1673&hei=1353&fmt=jpeg&qlt=95&.v=1527703100142",
    picture2: "https://m.media-amazon.com/images/I/51UCvY6cOGL._AC_SX679_.jpg",
    picture3: "https://m.media-amazon.com/images/I/71fwbMm1NBL._AC_SX342_.jpg",
    name: "Apple Watch série 3",
    systeme: "WatchOS 4",
    systeme_compatible: "iOS 11",
    nombre_de_coeur: 2,
    processeur: "Apple S2",
    capacite_de_stockage_disponible: "16 Mo",
    clavier: "Non",
    couleur: "Noire, Blanche, Blue, Rouge, Vert, Violet",
    tactile: "Oui",
    definition_de_l_écran: "312*390",
    reseau_wifi_supporte: "WI-Fi 802.11n",
    support_GPS: "Oui",
    fonction_appareil_photo: "Non",
    poids: "52,8 grammes",
    prix: "",
  },
  {
    id: 4,
    picture1:
      "https://www.apple.com/newsroom/images/product/watch/standard/apple-watch-series4_gold-stainless-steel_09122018_carousel.jpg.large.jpg",
    picture2:
      "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/FWVF2?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1580325951999",
    picture3:
      "https://www.apple.com/newsroom/images/product/watch/standard/apple-watch-series4_walkie-talkie_09122018_carousel.jpg.large.jpg",
    name: "Apple Watch série 4",
    systeme: "WatchOS 5",
    systeme_compatible: "iOS 12",
    nombre_de_coeur: 2,
    processeur: "Apple S4",
    capacite_de_stockage_disponible: "16 Go",
    clavier: "Non",
    couleur: "Noire, Blanche, Blue, Rouge, Vert, Violet",
    tactile: "Oui",
    definition_de_l_écran: "OLED",
    reseau_wifi_supporte: "WI-Fi 802.11n",
    support_GPS: "Oui",
    fonction_appareil_photo: "Non",
    poids: "47,9 grammes",
    prix: "",
  },
  {
    id: 5,
    picture1:
      "https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch_series_5-space-black-titanium-case-viper-dark-091019_carousel.jpg.large.jpg",
    picture2:
      "https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch_series_5-silver-aluminum-case-camel-band-091019_carousel.jpg.large.jpg",
    picture3:
      "https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch_series_5-nike-sports-band-royal-pulse-black-091019_carousel.jpg.large.jpg",
    name: "Apple Watch série 5",
    systeme: "WatchOS 6",
    systeme_compatible: "iOS",
    nombre_de_coeur: 2,
    processeur: "Apple S4",
    capacite_de_stockage_disponible: "32 Go",
    clavier: "Non",
    couleur: "Noire, Blanche, Blue, Rouge, Vert, Violet",
    tactile: "Oui",
    definition_de_l_écran: "448*368",
    reseau_wifi_supporte: "WI-Fi 802.11n",
    support_GPS: "Oui",
    fonction_appareil_photo: "Non",
    poids: "47,8 grammes",
    prix: "",
  },
  {
    id: 6,
    picture1:
      "https://www.cdiscount.com/pdt2/2/4/6/1/700x700/app0194252588246/rw/apple-watch-series-7-gps-41mm-boitier-midnight.jpg",
    picture2:
      "https://www.cdiscount.com/pdt2/2/4/6/1/700x700/app0194252588246/rw/apple-watch-series-7-gps-41mm-boitier-midnight.jpg",
    picture3: "https://m.media-amazon.com/images/I/71QfZshbZEL._AC_UL320_.jpg",
    name: "Apple Watch SE",
    systeme: "WatchOS 6",
    systeme_compatible: "iOS",
    nombre_de_coeur: 2,
    processeur: "Apple S5",
    capacite_de_stockage_disponible: "32 Go",
    clavier: "Non",
    couleur: "Noire, Blanche, Blue, Rouge, Vert, Violet",
    tactile: "Oui",
    definition_de_l_écran: "448*368",
    reseau_wifi_supporte: "WI-Fi 802.11n",
    support_GPS: "Oui",
    fonction_appareil_photo: "Non",
    poids: "36,4 grammes",
    prix: "",
  },
  {
    id: 7,
    picture1:
      "https://images.frandroid.com/wp-content/uploads/2020/09/apple-watch-series-6-frandroid-2020.png",
    picture2:
      "https://www.club-achat-cameroun.com/wp-content/uploads/products/apl0/APL0190199882461.jpg",
    picture3:
      "https://static.fnac-static.com/multimedia/Images/FR/MDM/c2/c9/8d/9292226/1505-1/tsp20220617173954/Apple-Watch-Series-6-GPS-44mm-boitier-aluminium-or-avec-bracelet-sport-rose.jpg",
    name: "Apple Watch Série 6",
    systeme: "WatchOS 6",
    systeme_compatible: "iOS",
    nombre_de_coeur: 2,
    processeur: "Apple S5",
    capacite_de_stockage_disponible: "32 Go",
    clavier: "Non",
    couleur: "Noire, Blanche, Blue, Rouge, Vert, Violet",
    tactile: "Oui",
    definition_de_l_écran: "448*368",
    reseau_wifi_supporte: "WI-Fi 802.11n",
    support_GPS: "Oui",
    fonction_appareil_photo: "Non",
    poids: "36,4 grammes",
    prix: "",
  },
  {
    id: 8,
    picture1:
      "https://images.frandroid.com/wp-content/uploads/2021/09/apple-watch-series-7-2021-frandroid.png",
    picture2:
      "https://www.cdiscount.com/pdt2/0/0/1/1/700x700/app0194252594001/rw/apple-watch-series-7-gps-45mm-boitier-starligh.jpg",
    picture3:
      "https://www.cdiscount.com/pdt2/2/4/6/1/700x700/app0194252588246/rw/apple-watch-series-7-gps-41mm-boitier-midnight.jpg",
    name: "Apple Watch Série 7",
    systeme: "WatchOS ",
    systeme_compatible: "iOS",
    nombre_de_coeur: 2,
    processeur: "Apple S5",
    capacite_de_stockage_disponible: "32 Go",
    clavier: "Non",
    couleur: "Noire, Blanche, Blue, Rouge, Vert, Violet",
    tactile: "Oui",
    definition_de_l_écran: "448*368",
    reseau_wifi_supporte: "WI-Fi 802.11n",
    support_GPS: "Oui",
    fonction_appareil_photo: "Non",
    poids: "51,5 grammes",
    prix: "",
  },
];
